### ISSUE TITLE
ident a wordpot

### ISSUE THREAD

**Issue by gregtampa** [gbrindisi/wordpot#10]
after scanning a server I can see the webserver info is Werkzeug/0.10.4 Python/2.7.3
So if i see this I know not to "hack" it and its a trap...
Is there a way to change the info for the webserver identifying itself?

**Comment by gregtampa** [comment]
I do see: SERVER      = 'Apache/2.2.22 (Ubuntu)'   # Custom server header
but this is not being shown. let me check my configs

**Comment by gregtampa** [comment]
ok it seems someone already added custom header support. I will patch

**Comment by gbrindisi** [comment]
It's been added here: https://github.com/gbrindisi/wordpot/commit/ca12cb56c89c7f3c8bba182b15e99ba3a60ce0c1

Nonetheless the anti fingerprint is very basic and could use some improvements, if you have ideas or patches feel free to send them my way. 

Cheers :sparkles:

**Comment by gregtampa** [comment]
I updated __init__.py and wordpot.conf files with the new code.
I stil get the Werkzeug/0.10.4 Python/2.7.3, I will pull a complete repo and test.
My tool i'm using to get the identity is very good to be fair on the test.
I'll post my results in a few minutes if I don't break my MHN integration

**Comment by gbrindisi** [comment]
What tool is it?

Also I doubt this patch has been pushed to MHN yet. cc: @jt6211

**Comment by gregtampa** [comment]
I'm using Cobalt Strike to do my scans.
No MHN has not updated. I'm trying to update myself but got an error debugging now.

**Comment by gregtampa** [comment]
Issue has been resolved.. if anyone wants to update this to MHN that would be nice. 
If you run MHN you can just clone this git and copy the env folder in

**Comment by jt6211** [comment]
MHN updated https://github.com/threatstream/wordpot/pull/2.  Thanks.

Sensor can be updated like this:

```
cd /opt/wordpot
sudo git fetch origin
sudo git merge origin/master
sudo supervisorctl restart wordpot
```
