### ISSUE TITLE
Wordpot fingerprinting

### ISSUE THREAD

**Issue by R-eyes** [gbrindisi/wordpot#9]
It seems that this honeypot does not attract attackers on my servers unlike other web services honeypots. (glastopf, shockpot)

Possible reason is that this honeypot shows the following fingerprint on nmap scan for port 80:
80/tcp open  http    Werkzeug httpd 0.10.4 (Python 2.7.6)

(Honeypots like glastopf or shockpot show Apache httpd 2.x.x fingerprints.) 

it would be possible to add a similar fingerprint for wordpot ?

**Comment by gbrindisi** [comment]
That is spot on. I'll look into this.

**Comment by gbrindisi** [comment]
I've added support for custom Server header with a `Apache/2.2.22 (Ubuntu)` as default.
Have a look: https://github.com/gbrindisi/wordpot/commit/ca12cb56c89c7f3c8bba182b15e99ba3a60ce0c1
